export const initialFormData = {
  currentStep: 1,
  openIndex: 1,
  consignorDetail: {
    pickupAddress: "",
    selectedUserDetail: "",
  },
  consigneeDetail: {
    firstName: "",
    lastName: "",
    mobileNumber: "",
    alternateMobileNumber: "",
    email: "",
    country: "",
    landMark: "",
    address1: "",
    address2: "",
    shippingcity: "",
    shippingPincode: "",
    shippingState: "",
    billingfirstName: "",
    billinglastName: "",
    billingmobileNumber: "",
    billingCountry: "",
    billingLandMark: "",
    billingAddress1: "",
    billingAddress2: "",
    billingcity: "",
    billingPincode: "",
    billingState: "",
  },
  shipmentInformation: {
    actualWeight: "",
    length: "",
    breadth: "",
    height: "",
    invoiceNo: "",
    invoiceCurrency: "",
    orderId: "",
    invoiceDate: "",
    orderid: "",
    items: [
      {
        productName: "",
        sku: "",
        hsn: "",
        qty: "",
        unitPrice: "",
        igst: "",
      },
    ],
  },
  selectShippingPartner: { shippingPartner: "", est: "", price: "" },
};
